apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "seo2.configMapName" . }}
  namespace: {{ include "seo2.namespace" . }}
  labels:
    {{- include "seo2.labels" . | nindent 4 }}
data:
  config.json: |
    {{- toPrettyJson .Values.config | nindent 4 }}
