{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "seo2.serviceAccountName" . }}
  namespace: {{ include "seo2.namespace" . }}
  labels:
    {{- include "seo2.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "seo2.clusterRoleBindingName" . }}
  namespace: {{ include "seo2.namespace" . }}
  labels:
  {{- include "seo2.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: {{ include "seo2.serviceAccountName" . }}
    namespace: {{ include "seo2.namespace" . }}
{{- end }}
